/// <reference path="c:\program files\hexagon\edgecam 2023.1\cam\PCI\pci-vsdoc.js" />
var cmd1 = InitCommand(2, 1002); 
ClearMods(cmd1); 
SetModifier(cmd1, 4, "30"); 
SetModifier(cmd1, 5, "30"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 1, "Gold|21"); 
SetModifier(cmd1, 2, "Solid|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoCoordStr(_DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, "X-150");
AddDigInfoPortNumber(1);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(2, 1); 
ClearMods(cmd1); 
SetModifier(cmd1, 155, "0"); 
SetModifier(cmd1, 4, "<Yes>"); 
SetModifier(cmd1, 1, "Gold|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "Solid|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoConstructRef(_CMD_MIDPOINT, 1);
AddDigInfoComponentInfo(_DIG_3DSNAP, _ENTITYDIG, 2);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 4, 0), _DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigInfoPortNumber(0);
AddDigArray(gdh1);
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoConstructRef(_CMD_MIDPOINT, 1);
AddDigInfoComponentInfo(_DIG_3DSNAP, _ENTITYDIG, 2);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 2, 0), _DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigInfoPortNumber(0);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(2, 1); 
ClearMods(cmd1); 
SetModifier(cmd1, 155, "0"); 
SetModifier(cmd1, 5, "<Yes>"); 
SetModifier(cmd1, 1, "Gold|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "Solid|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoConstructRef(_CMD_MIDPOINT, 1);
AddDigInfoComponentInfo(_DIG_3DSNAP, _ENTITYDIG, 2);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 3, 0), _DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigInfoPortNumber(0);
AddDigArray(gdh1);
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoConstructRef(_CMD_MIDPOINT, 1);
AddDigInfoComponentInfo(_DIG_3DSNAP, _ENTITYDIG, 2);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 1, 0), _DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigInfoPortNumber(0);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(2, 2); 
ClearMods(cmd1); 
SetModifier(cmd1, 104, "5"); 
SetModifier(cmd1, 1, "Gold|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "Solid|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _FREEDIG);
AddDigInfoConstructRef(_CMD_MIDPOINT, 1);
AddDigInfoComponentInfo(_DIG_3DSNAP, _ENTITYDIG, 2);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 5, 0), _DIG_3DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigInfoPortNumber(0);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(1, 1); 
ClearMods(cmd1); 
SetModifier(cmd1, 154, "30"); 
SetModifier(cmd1, 243, "3"); 
SetModifier(cmd1, 1, "21|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "0|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _ENTITYDIG);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 6, 0), _DIG_2DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_FORWARD);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(1, 1); 
ClearMods(cmd1); 
SetModifier(cmd1, 154, "30"); 
SetModifier(cmd1, 243, "3"); 
SetModifier(cmd1, 1, "21|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "0|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _ENTITYDIG);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 1, 5, 0), _DIG_2DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_REVERSE);
AddDigArray(gdh1);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(10, 69); 
ClearMods(cmd1); 
var gdh1 = InitDigInfo();
AddEntnoDig(gdh1, FindEntityNo(_FINDENTNO_FROM_BASEENT, 16385, 1, 0), _DIR_FORWARD, _DIG_3DSNAP);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(10, 69); 
ClearMods(cmd1); 
var gdh1 = InitDigInfo();
AddEntnoDig(gdh1, FindEntityNo(_FINDENTNO_FROM_BASEENT, 16385, 1, 0), _DIR_FORWARD, _DIG_3DSNAP);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(10, 69); 
ClearMods(cmd1); 
var gdh1 = InitDigInfo();
AddEntnoDig(gdh1, FindEntityNo(_FINDENTNO_FROM_BASEENT, 16385, 1, 0), _DIR_FORWARD, _DIG_3DSNAP);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(10, 69); 
ClearMods(cmd1); 
var gdh1 = InitDigInfo();
AddEntnoDig(gdh1, FindEntityNo(_FINDENTNO_FROM_BASEENT, 16385, 3, 0), _DIR_FORWARD, _DIG_3DSNAP);
AddFinishDig(gdh1, _FINISH);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

var cmd1 = InitCommand(1, 2); 
ClearMods(cmd1); 
SetModifier(cmd1, 6, "0"); 
SetModifier(cmd1, 7, "360"); 
SetModifier(cmd1, 104, "6"); 
SetModifier(cmd1, 1, "21|21"); 
SetModifier(cmd1, 3, "Geometry"); 
SetModifier(cmd1, 2, "0|0"); 
var gdh1 = InitDigInfo();
BeginDigArray(gdh1, _ENTITYDIG);
AddDigInfoEntnoDig(FindEntityNo(_FINDENTNO_FROM_BASEENT, 2, 1, 0), _DIG_2DSNAP+_DIG_TANGENT+_DIG_2DCHAIN, _DIR_REVERSE);
AddDigArray(gdh1);
var cmdret = ExecCommand(cmd1, gdh1); 
FreeDigInfo(gdh1); 

